application:
    name: EMonDeviceRegistration
error:
  whitelabel:
    enabled: false
logging:
  level:
     root: info
spring: 
  flyway:
    locations: db.migration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none    
