application:
    name: EMonDeviceRegistration
error:
  whitelabel:
    enabled: false
logging:
  level:
     root: debug
spring: 
  flyway:
    locations: db.migration
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate    
